(part "46010-0622"
    (packageRef "46010-06YY")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-46010-0622")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=538-46010-0622")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "46010-0622")
    (property "Description" "Mini-Fit Plus PCB Receptacle, 4.20mm Pitch, Dual Row, Vertical, Blind Mating, 6 Circuits, with Snap-in Plastic Peg PCB Lock, PA Polyamide Nylon 6/6, UL 94V-2")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/46010-0622.pdf")
    (property "symbolName1" "46010-0622")
)
