(part "212520-1006"
    (packageRef "212520-1006")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-212520-1006")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/212520-1006?qs=pUKx8fyJudA8jKWmA%2FIrSg%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "212520-1006")
    (property "Description" "Mini-Fit Max Vertical Header, Dual Row, 12 Circuits, Tin (Sn) Plating, Black")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/2125201006_sd.pdf")
    (property "symbolName1" "212520-1006")
)
